project:
  name: "HiddenReasoning1"
  experiment_name: "TestQwen"
  hf_checkpoint: "HiddenReasoning1-TestQwen"


model:
  name: Qwen/Qwen3-8B
  dtype: "bfloat16"
  device_map: "cuda"
  special_tokens:
    - "[END]"
  attn_implementation: "eager"

dataset:
  name: "/data"
  train_size: 12000
  eval_size: 2000
  max_length: 500
  K: 15

peft:
  r: 8
  lora_alpha: 8
  lora_dropout: 0.05
  bias: "lora_only"
  task_type: "CAUSAL_LM"
  use_rslora: false
  target_modules:
    - "q_proj"
    - "k_proj"
    - "v_proj"
    - "gate_proj"
    - "up_proj"
    - "down_proj"
    - "o_proj"

trainer:
  output_dir: "./output"
  num_train_epochs: 8
  per_device_train_batch_size: 2
  gradient_accumulation_steps: 1
  learning_rate: 3e-4
  weight_decay: 0.01
  lr_scheduler_type: "linear"
  warmup_steps: 100
  logging_steps: 10
  save_steps: 10000
  bf16: true
  tf32: true
  gradient_checkpointing: false
  optim: "adamw_torch"
  report_to: "none"
  max_grad_norm: 0.3
  ddp_find_unused_parameters: false
  push_to_hub: false
  hub_model_id: ${project.hf_checkpoint}
  eval_strategy: "epoch"
  remove_unused_columns: false
  